import json

from typing import Any, Dict
from dotenv import load_dotenv
from engine.ai_config import (
    build_system_prompt_from_config,
    get_prompt,
    WorkloadLabelOutput,
)
from engine.util import load_config, get_logger
from langsmith import traceable

from engine.client import get_client

logger = get_logger("langgraph_agents")

load_dotenv()


class LLMInvokeModel:
    """
    Lightweight wrapper exposing a LangChain-like `.invoke(input)` interface,
    backed by our AI Client (OpenAI compatible — works with Ollama, OpenRouter, etc.).
    """

    def __init__(
        self, client, model_name: str, system_prompt: str, **gen_cfg
    ):
        self._client = client
        self._model_name: str = model_name
        self._system_prompt: str = system_prompt
        # Normalize generation config keys to OpenAI chat params
        self._gen_cfg: Dict[str, Any] = {
            "temperature": gen_cfg.get("temperature", 0.1),
            # In config we may store as max_output_tokens; OpenAI param is max_tokens
            "max_tokens": gen_cfg.get("max_output_tokens", 2048),
        }

    def invoke(self, user_prompt: str) -> str:
        return self._client.chat_structured(
            model=self._model_name,
            system_prompt=self._system_prompt,
            user_prompt=user_prompt,
            schema=WorkloadLabelOutput.model_json_schema(),
            **self._gen_cfg,
        )


def get_llm():
    """Initialize and return a model wrapper with `.invoke` and its config."""
    try:
        client = get_client()
        config = load_config()
        selected_model = config["ai"].get("selected_model", "qwen3:8b")
        model_cfg = config["ai"]["default_config"]

        if model_cfg is None:
            raise ValueError(f"Model '{selected_model}' not found in configuration.")

        model_name = selected_model
        # Work on a mutable copy to avoid mutating global config inadvertently
        generation_config = dict(model_cfg.get("generation_config", {}))

        # Extract system prompt then remove it so it is not forwarded twice via **kwargs
        system_prompt = build_system_prompt_from_config()

        generation_config.pop("system_prompt", None)
        generation_config.pop("rules", None)

        model = LLMInvokeModel(
            client, model_name, system_prompt, **generation_config
        )
        return model
    except Exception as e:
        logger.error(f"Failed to initialize AI client/model: {e}")
        raise ValueError(f"Failed to initialize AI client/model: {e}")


model = get_llm()


# -----------------------
# Langraph agents
# -----------------------
@traceable(name="recommendations_node")
def recommendationsNode(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Invokes the LLM to generate migration recommendations and explanations.
    """
    workloads = state.get("workloads", [])
    clusters = state.get("cluster_info", [])

    # Tool nodes key their results by the timestamps present in the input data;
    # the graph feeds them under "latest" (see tool_system_graph.py).
    pending_all_timestamps = state.get("pending_by_workload", {}) or {}

    if "latest" in pending_all_timestamps:
        pending_latest = pending_all_timestamps["latest"]
    else:
        valid_timestamps = [
            key for key in pending_all_timestamps.keys() if str(key).isdigit()
        ]
        pending_latest = (
            pending_all_timestamps.get(max(valid_timestamps, key=int), {})
            if valid_timestamps
            else {}
        )

    for w in workloads:
        workload_id = w.get("workload_id")
        w["percent_pending"] = pending_latest.get(
            workload_id, w.get("percent_pending", "0%")
        )

    analysis_results = {
        key: state.get(key)
        for key in (
            "cluster_capacity",
            "pending_by_cluster",
            "workload_capacity",
            "workload_pricing",
            "infra_pricing",
        )
        if state.get(key)
    }

    prompt_data = {
        "workloads_json": json.dumps(workloads, indent=2),
        "clusters_json": json.dumps(clusters, indent=2),
        "pending_json": json.dumps(pending_all_timestamps, indent=2),
        "analysis_json": json.dumps(analysis_results, indent=2),
    }

    prompt = get_prompt("label_workloads_tools", **prompt_data)
    resp = model.invoke(prompt)


    try:
        # `chat_structured` may already return a parsed dict; fall back to JSON parse otherwise
        parsed = resp if isinstance(resp, dict) else json.loads(resp)
        wl_output = WorkloadLabelOutput.from_dict(parsed)
        decisions_list = wl_output.decisions
        explanations_list = wl_output.explanations
        overall_explanation = parsed.get(
            "overall_explanation", "Migration decisions generated by LLM"
        )
    except (Exception,):
        # Fallback path when response is not valid or schema fails
        logger.error(
            "LLM failed to generate a valid WorkloadLabelOutput."
        )
        decisions_list = [-1] * len(workloads)
        explanations_list = [
            "RecommendationsNode failed to produce WorkloadLabelOutput"
            for _ in workloads
        ]
        overall_explanation = (
            "RecommendationsNode failed to produce WorkloadLabelOutput"
        )

    final_decisions: list[int] = []
    workload_explanations: list[str] = []

    for label, expl in zip(decisions_list, explanations_list):
        label_int = -1 

        try:
            
            val = int(label)
            
            
            if val in [0, 1]:
                label_int = val
            elif val == -1:
                label_int = -1 
            else:
                
                logger.warning(f"Label value {val} outside of expected range [0, 1, -1]. Setting to -1.")
                label_int = -1
                
        except (ValueError, TypeError):
            
            logger.warning(f"Non-numeric label received: {label}. Setting to -1.")
            label_int = -1
            
        final_decisions.append(label_int)
        workload_explanations.append(expl)

    state["decisions"] = final_decisions
    state["explanations"] = {
        "overall_explanation": overall_explanation,
        "workload_explanations": workload_explanations,
    }

    return state
